version: '2'
services:

  mosquitto:
    image: eclipse-mosquitto:1.5
    ports:
    - "1883:1883"
    - "9001:9001"
    volumes:
    - ./mosquitto/data:/mosquitto/data

  opensensemap:
    build: ./opensensemap
    links:
    - "mosquitto"

  homekit2mqtt:
    build: ./homekit2mqtt/image
    network_mode: host
    volumes:
    - ./homekit2mqtt/data:/homekit2mqtt/data
    - ./homekit2mqtt/config:/homekit2mqtt/config
    - /var/run/dbus:/var/run/dbus

  mirobo:
    build: ./mirobo
    links:
    - "mosquitto"
