version: '2'
services:

  mosquitto:
    image: eclipse-mosquitto:1.5
    ports:
    - "1883:1883"
    - "9001:9001"
    volumes:
    - ./mosquitto/data:/mosquitto/data

  opensensemap:
    build: ./opensensemap
    command: ["58d42511c877fb0011ad4597"]
    links:
      - "mosquitto"