version: '2'
services:

  mosquitto:
    image: eclipse-mosquitto:1.5
    ports:
    - "1883:1883"
    - "9001:9001"
    volumes:
    - ./mosquitto/data:/mosquitto/data

  opensensemap:
    build: ./opensensemap
    links:
    - "mosquitto"

  homekit2mqtt:
    build: ./homekit2mqtt/image
    network_mode: host
    volumes:
    - ./homekit2mqtt/data:/homekit2mqtt/data
    - ./homekit2mqtt/config:/homekit2mqtt/config
    - /var/run/dbus:/var/run/dbus

  mirobo:
    build: ./mirobo
    links:
    - "mosquitto"
    environment:
    - MIROBO_IP=rockrobo

  influxdb:
    build: ./influxdb/image
    ports:
    - "8086:8086"
    volumes:
    - ./influxdb/data:/var/lib/influxdb
    - ./influxdb/config/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    - /etc/localtime:/etc/localtime:ro

  telegraf:
    build: ./telegraf/image
    links:
    - "mosquitto"
    - "influxdb"
    volumes:
    - ./telegraf/config:/etc/telegraf:ro

  miflora:
    build: ./miflora/image
    network_mode: host
    volumes:
    - ./miflora/config/config.ini:/usr/src/app/config.ini:ro
